const reviews = [
    {
      id: 1,
      name: 'Dhaval Jardosh',
      job: 'web developer',
      image: 'https://avatars.githubusercontent.com/u/18078687?v=4',
      gitLink: 'https://github.com/dhavaljardosh',
      text: "I'm baby meggings twee health goth +1. Bicycle rights tumeric chartreuse before they sold out chambray pop-up. Shaman humblebrag pickled coloring book salvia hoodie, cold-pressed four dollar toast everyday carry",
    },
    {
      id: 2,
      name: 'John Smilga',
      job: 'web designer',
      image: 'https://avatars.githubusercontent.com/u/42133389?v=4',
      gitLink: 'https://github.com/dashboard',
      text: 'Helvetica artisan kinfolk thundercats lumbersexual blue bottle. Disrupt glossier gastropub deep v vice franzen hell of brooklyn twee enamel pin fashion axe.photo booth jean shorts artisan narwhal.',
    },
    {
      id: 3,
      name: 'Rishikesh Pal',
      job: 'Backend',
      image: 'https://avatars.githubusercontent.com/u/45008954?v=4',
      gitLink: 'https://github.com/palrishikesh',
      text: 'Sriracha literally flexitarian irony, vape marfa unicorn. Glossier tattooed 8-bit, fixie waistcoat offal activated charcoal slow-carb marfa hell of pabst raclette post-ironic jianbing swag.',
    },
    {
      id: 4,
      name: 'Nikesh Kumar',
      job: 'the Admin',
      image: 'https://avatars.githubusercontent.com/u/112698036?v=4',
      gitLink: 'https://github.com/nikeshgitpro611',
      text: 'Edison bulb put a bird on it humblebrag, marfa pok pok heirloom fashion axe cray stumptown venmo actually seitan. VHS farm-to-table schlitz, edison bulb pop-up 3 wolf moon tote bag street art shabby chic. ',
    },
    {
      id: 5,
      name: 'Muhammad Arsalan Manzoor',
      job: 'Web and Mobile App Developer',
      image: 'https://avatars.githubusercontent.com/u/44143816?v=4',
      gitLink: 'https://github.com/arsalan98m',
      text: 'Contributed to arsalan98m/flutter_rest_api, arsalan98m/flutter_navigation, arsalan98m/flutter_google_map and 6 other repositories ',
    },
    {
      id: 6,
      name: 'Priya Survase',
      job: 'Web Developer',
      image: 'https://github.com/devicons/devicon/raw/master/icons/react/react-original.svg',
      gitLink: 'https://github.com/priya-survase',
      text: 'A Food Delivery App created using ReactJS',
    },
    {
      id: 7,
      name: 'Academind',
      job: 'Web Developer',
      image: 'https://avatars.githubusercontent.com/u/28806202?s=200&v=4',
      gitLink: 'https://github.com/academind',
      text: 'A Food Delivery App created using ReactJS',
    },
    {
      id: 8,
      name: 'Adrian Hajdin',
      job: 'Adrian Hajdin - JS Mastery',
      image: 'https://avatars.githubusercontent.com/u/24898559?v=4',
      gitLink: 'https://github.com/adrianhajdin',
      text: 'This is a code repository for the corresponding video tutorial. Using React, Node.js, Express & MongoDB youll learn how to build a Full Stack MERN Application - from start to finish.',
    },
    {
      id: 9,
      name: 'CoderDost',
      job: 'CoderDost - Full Stack',
      image: 'https://avatars.githubusercontent.com/u/76863264?s=200&v=4',
      gitLink: 'https://github.com/coderdost',
      text: 'CoderDost Coder Dost YouTube Channel',
    },
    {
      id: 10,
      name: 'Abhishek Singh',
      job: 'Full Stack',
      image: 'https://avatars.githubusercontent.com/u/25058652?v=4',
      gitLink: 'https://github.com/meabhisingh',
      text: ' YouTube Channel',
    },
    {
      id: 11,
      name: 'Bhagirath WsCube Tech',
      job: 'javascript-projects',
      image: 'https://avatars.githubusercontent.com/u/87521863?v=4',
      gitLink: 'https://github.com/bhagirath-wscubetech',
      text: ' YouTube Channel',
    },
  ];

  export default reviews;